// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JumiaSignInValidationsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signInInValidEmailValidPassword() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.antolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("mypassword");
    driver.findElement(By.cssSelector(".-mts > span")).click();
    assertThat(driver.switchTo().alert().getText(), is("Cannot contact reCAPTCHA. Check your connection and try again."));
    driver.findElement(By.cssSelector(".-mts")).click();
    driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).getText(), is("Incorrect E-mail or Password"));
  }
  @Test
  public void signInValidEmailInValidPassword() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-fg1 > .fi-w:nth-child(1) > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("adaobi");
    driver.findElement(By.cssSelector(".-mts")).click();
    {
      WebElement element = driver.findElement(By.linkText("Forgot your password?"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("authForm")).click();
    driver.findElement(By.cssSelector(".-vr")).click();
    driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).getText(), is("Incorrect E-mail or Password"));
  }
  @Test
  public void signUp() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("mypassword");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.cssSelector(".-mvs")).click();
  }
  @Test
  public void signInBlankEmailBlankPassword() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mts")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".-mts"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".-vr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".-vr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".-vr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".-vr")).click();
    driver.findElement(By.cssSelector(".-vr")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signInForgotEmailNotCorrectFormat() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@");
    driver.findElement(By.id("fi-password")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself");
    driver.findElement(By.cssSelector(".-mts > span")).click();
    driver.findElement(By.id("authForm")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Invalid Information"));
  }
  @Test
  public void signInForgotPassWord() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic > use")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.id("fi-password")).click();
    driver.findElement(By.linkText("Forgot your password?")).click();
    driver.findElement(By.cssSelector(".lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".-pvm > .btn")).click();
  }
  @Test
  public void signInLoginWithFacebook() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(5) > span")).click();
    driver.findElement(By.cssSelector(".bwm1u5wc > .a8c37x1j")).click();
  }
  @Test
  public void signUpInvalidEmailFormat() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-fg1 > .fi-w:nth-child(1) > .lbl")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("inteochi");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("olami520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Invalid Information"));
  }
  @Test
  public void signUpEmailAlreadyExists() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".-fw:nth-child(1) > .card > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".-mtxl > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("inteochi@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("E-mail already in use"));
  }
  @Test
  public void signUpNumbersinFirstNmaeLastNameField() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("12546885");
    driver.findElement(By.id("fi-firstName")).sendKeys("12546821");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("25555");
    driver.findElement(By.id("fi-lastName")).sendKeys("25555899");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("inteochi@gmall.com");
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("myteochi@gmall.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
  }
  @Test
  public void signUpNumbersInFirstNameField() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".itm:nth-child(6) > .-fw .-rad4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fi-w .ic"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("12546885");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("inteochi@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
  }
  @Test
  public void signUpNumbersinLastNameField() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("25555");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("inteochi@gmail.com");
    driver.findElement(By.id("fi-email")).sendKeys("inteochi@gmall.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
  }
  @Test
  public void signInInValidEmailInValidPassword() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.atnonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("adeola");
    driver.findElement(By.cssSelector(".-mts")).click();
    driver.findElement(By.id("authForm")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).getText(), is("Incorrect E-mail or Password"));
  }
  @Test
  public void signUpAlphaNumericPhoneNumber() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    {
      WebElement element = driver.findElement(By.id("fi-password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fi-br > .lbl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".fi-br")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("myteochi@gball.com");
    driver.findElement(By.cssSelector(".-mlm > .lbl")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("01254hr");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    driver.findElement(By.id("authForm")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Invalid Information"));
  }
  @Test
  public void signUpNewsLetterUnchecked() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    {
      WebElement element = driver.findElement(By.id("fi-lastName"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2)")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    js.executeScript("window.scrollTo(0,300)");
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig > .ic")).click();
    driver.findElement(By.cssSelector(".-mvs")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
  @Test
  public void signUpPasswordVisibleButtonChecked() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-fg1 > .fi-w:nth-child(1) > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".fi-w > button")).click();
    assertTrue(driver.findElement(By.cssSelector(".fi-w > button")).isSelected());
  }
  @Test
  public void signUpTermsandConditionsNotAccepted() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".-mlm > .lbl")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("080253358615");
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpAllFieldsBlank() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".-ptl > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_cb > .fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_cb > .fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpEmailBlank() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".col10:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpFirstNameBlank() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".fi-w > button")).click();
    driver.findElement(By.cssSelector(".fi-w > button")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".-ptl > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#authForm > .col10:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#authForm > .col10:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#authForm > .col10:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("#authForm > .col10:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpLasttNameBlank() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    {
      WebElement element = driver.findElement(By.id("fi-password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fi-br > .lbl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".fi-br")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myslelf520");
    driver.findElement(By.id("fi-phone")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("08060558445");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.id("fi-phone")).click();
    driver.findElement(By.id("fi-phone")).click();
    {
      WebElement element = driver.findElement(By.id("fi-phone"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("fi-phone")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("08060123456");
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpPasswordBlank() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    {
      WebElement element = driver.findElement(By.id("fi-phone"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".-mlm > .lbl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".-mlm")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("08060558445");
    driver.findElement(By.id("fi-phone")).sendKeys("08060123456");
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Required field"));
  }
  @Test
  public void signUpPhoneNumberDoublePrefix() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    {
      WebElement element = driver.findElement(By.linkText("My Account"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("fi-email")).sendKeys("Olaoye");
    driver.findElement(By.id("fi-password")).sendKeys("B8AZU7UZsN.hdDD");
    driver.findElement(By.cssSelector(".-mtxl > span")).click();
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-firstName")).click();
    driver.findElement(By.id("fi-firstName")).sendKeys("Anthony");
    driver.findElement(By.cssSelector(".col10:nth-child(2) > .fi-w:nth-child(2) > .lbl")).click();
    driver.findElement(By.id("fi-lastName")).click();
    driver.findElement(By.id("fi-lastName")).sendKeys("Olaoye");
    driver.findElement(By.cssSelector(".col10:nth-child(3) > .-mrl > .lbl")).click();
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildeca@gmail.com");
    driver.findElement(By.id("fi-email")).click();
    driver.findElement(By.id("fi-email")).sendKeys("maildec@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("myself520");
    driver.findElement(By.cssSelector(".-mlm > .lbl")).click();
    driver.findElement(By.id("fi-phone")).sendKeys("2348060558445");
    driver.findElement(By.cssSelector(".col10:nth-child(5) .lbl")).click();
    driver.findElement(By.id("authForm")).click();
    driver.findElement(By.cssSelector(".-ptl > .btn")).click();
    driver.findElement(By.cssSelector(".fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-er")).getText(), is("Invalid Phone Number"));
  }
}
