// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignInValidEmailWrongPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signInValidEmailWrongPassword() {
    driver.get("https://www.jumia.com.ng/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".dpdw:nth-child(1) > .trig")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.cssSelector(".-fg1 > .fi-w:nth-child(1) > .lbl")).click();
    driver.findElement(By.id("fi-email")).sendKeys("mail.anthonyolaoye@gmail.com");
    driver.findElement(By.cssSelector(".fi-br > .lbl")).click();
    driver.findElement(By.id("fi-password")).sendKeys("adaobi");
    driver.findElement(By.cssSelector(".-mts")).click();
    {
      WebElement element = driver.findElement(By.linkText("Forgot your password?"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("authForm")).click();
    driver.findElement(By.cssSelector(".-vr")).click();
    driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).click();
    assertThat(driver.findElement(By.cssSelector(".fi-w:nth-child(1) > .fi-er")).getText(), is("Incorrect E-mail or Password"));
  }
}
